In [3]:
import requests
import pandas as pd

# === CONFIGURATION ===
REPOS = [
    "fuzzygroup/polly",
    "fuzzygroup/policounter"
]

# Optional: GitHub token for higher rate limits
GITHUB_TOKEN = None  # e.g., "ghp_xxx" or set via env var

HEADERS = {
    "Accept": "application/vnd.github+json",
}
if GITHUB_TOKEN:
    HEADERS["Authorization"] = f"Bearer {GITHUB_TOKEN}"

def fetch_issues(repo):
    url = f"https://api.github.com/repos/{repo}/issues?state=open&per_page=100"
    response = requests.get(url, headers=HEADERS)
    response.raise_for_status()
    issues = response.json()

    # Filter out pull requests
    issues = [i for i in issues if "pull_request" not in i]

    # Flatten data
    rows = []
    for i in issues:
        rows.append({
            "repo": repo,
            "id": i["number"],
            "title": i["title"],
            "assignees": [a["login"] for a in i["assignees"]],
            "labels": [label["name"] for label in i["labels"]],
            "state": i["state"],
            "created_at": i["created_at"],
            "url": i["html_url"]
        })

    return pd.DataFrame(rows)

# === MAIN ===
all_dfs = []
for repo in REPOS:
    print(f"Fetching issues from: {repo}")
    df = fetch_issues(repo)
    all_dfs.append(df)
    # Optionally save per repo
    df.to_csv(f"{repo.replace('/', '_')}_issues.csv", index=False)

# Combine all into one dataframe (optional)
combined_df = pd.concat(all_dfs, ignore_index=True)

Fetching issues from: fuzzygroup/polly
Fetching issues from: fuzzygroup/policounter

In [4]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)  

# Loop through each repo’s dataframe and display
for df in all_dfs:
    if df.empty:
        continue

    # Filter for issues with no assignees or assignee includes "tetrismegistus"
    filtered = df[df["assignees"].apply(lambda a: not a or "tetrismegistus" in a)]

    if filtered.empty:
        continue

    repo_name = filtered.repo.iloc[0]
    print(f"\n📌 Filtered Issues for: {repo_name}")
    display(filtered)

📌 Filtered Issues for: fuzzygroup/polly

,repo,id,title,assignees,labels,state,created_at,url
0,fuzzygroup/polly,78,Default the event state to be the current state where the user comes from based on a geocoding call,[tetrismegistus],[],open,2025-07-15T16:44:41Z,https://github.com/fuzzygroup/polly/issues/78
1,fuzzygroup/polly,76,Global code refactor as a learning tool for aric,[tetrismegistus],[enhancement],open,2025-07-03T08:57:08Z,https://github.com/fuzzygroup/polly/issues/76
2,fuzzygroup/polly,73,Prevent the event attendance / event volunteer / event speaker application buttons from showing up IF THE USER ALREADY DID THEM,[tetrismegistus],[],open,2025-06-26T09:13:46Z,https://github.com/fuzzygroup/polly/issues/73
3,fuzzygroup/polly,72,I want you to write us a rake task which finds problems in our forms,[tetrismegistus],[],open,2025-06-26T08:58:16Z,https://github.com/fuzzygroup/polly/issues/72
4,fuzzygroup/polly,71,JavaScript capture to cookie in the event of a crash on editing text fields,[tetrismegistus],[],open,2025-06-25T08:50:48Z,https://github.com/fuzzygroup/polly/issues/71
5,fuzzygroup/polly,70,Work with Alisa to produce a better looking (yes that's fucking nebulous) Event Attendance form,[tetrismegistus],[],open,2025-06-25T06:48:50Z,https://github.com/fuzzygroup/polly/issues/70
6,fuzzygroup/polly,69,Get Merit Gem working and Get past the Observers issue,[tetrismegistus],[],open,2025-06-24T08:03:00Z,https://github.com/fuzzygroup/polly/issues/69
7,fuzzygroup/polly,68,Integrate Rails Admin into Polly in a Branch,[tetrismegistus],[],open,2025-06-24T07:55:39Z,https://github.com/fuzzygroup/polly/issues/68
8,fuzzygroup/polly,67,Figure out how people can add their own profile images to Polly,[tetrismegistus],[],open,2025-06-24T07:50:04Z,https://github.com/fuzzygroup/polly/issues/67
10,fuzzygroup/polly,64,Protest Alert Feature,[tetrismegistus],[],open,2025-06-23T17:24:24Z,https://github.com/fuzzygroup/polly/issues/64
11,fuzzygroup/polly,63,Polly Videos,[tetrismegistus],[enhancement],open,2025-06-23T13:36:38Z,https://github.com/fuzzygroup/polly/issues/63
13,fuzzygroup/polly,60,Search Enhancements,[],[],open,2025-06-19T14:31:35Z,https://github.com/fuzzygroup/polly/issues/60
14,fuzzygroup/polly,57,JavaScript for setting height of textareas to be NOT FUCKING TINY,[tetrismegistus],[],open,2025-06-16T10:20:54Z,https://github.com/fuzzygroup/polly/issues/57
17,fuzzygroup/polly,54,Non Logged Interface for Polly is Find a Protest,[],[],open,2025-06-05T16:54:31Z,https://github.com/fuzzygroup/polly/issues/54
18,fuzzygroup/polly,53,"Add ""good person for this location"" feature to offline promotion locations model",[],[],open,2025-06-05T12:30:04Z,https://github.com/fuzzygroup/polly/issues/53
19,fuzzygroup/polly,52,Build a Press Mentions facility for tracking links to press stuff,[],[],open,2025-06-05T12:25:27Z,https://github.com/fuzzygroup/polly/issues/52
20,fuzzygroup/polly,51,Build a documents facility for capturing things like Beckwith Questions,[],[],open,2025-06-05T09:45:06Z,https://github.com/fuzzygroup/polly/issues/51
21,fuzzygroup/polly,50,Need a great print view to unify speaker and musician bios,[],[],open,2025-06-04T15:20:53Z,https://github.com/fuzzygroup/polly/issues/50
22,fuzzygroup/polly,49,Add support for chat input like mail,[],[],open,2025-06-04T15:20:08Z,https://github.com/fuzzygroup/polly/issues/49
23,fuzzygroup/polly,48,Implement a video gallery for shared video contribution,[],[],open,2025-06-04T15:19:39Z,https://github.com/fuzzygroup/polly/issues/48
24,fuzzygroup/polly,47,Implement a photo gallery for group photo contributions,[],[],open,2025-06-04T15:19:13Z,https://github.com/fuzzygroup/polly/issues/47
25,fuzzygroup/polly,46,Fix breadcrumb tracking to reflect nested resources,[tetrismegistus],[enhancement],open,2025-06-01T09:57:45Z,https://github.com/fuzzygroup/polly/issues/46
26,fuzzygroup/polly,45,MONDAY: Implement support for Meilli Search in Polly,[tetrismegistus],[enhancement],open,2025-05-31T12:42:37Z,https://github.com/fuzzygroup/polly/issues/45
27,fuzzygroup/polly,44,Add your count down timer to events on the events in the Polly software,[tetrismegistus],[enhancement],open,2025-05-31T12:41:00Z,https://github.com/fuzzygroup/polly/issues/44
36,fuzzygroup/polly,22,Add a flag or text display to the event schedule that indicates that after a certain date you cannot request to be a speaker,[tetrismegistus],[],open,2025-05-14T11:57:00Z,https://github.com/fuzzygroup/polly/issues/22
38,fuzzygroup/polly,17,Availabilities Model,[],[],open,2025-05-04T17:41:51Z,https://github.com/fuzzygroup/polly/issues/17
39,fuzzygroup/polly,16,Presentation of Rules,[],[],open,2025-05-04T17:41:16Z,https://github.com/fuzzygroup/polly/issues/16
40,fuzzygroup/polly,15,Write a memeorandum archiver and schedule it for 4x per day,[],[],open,2025-05-04T17:39:15Z,https://github.com/fuzzygroup/polly/issues/15
41,fuzzygroup/polly,14,Get Polly deployed onto a DO box or Hetzner box,[],[],open,2025-04-28T13:22:05Z,https://github.com/fuzzygroup/polly/issues/14
42,fuzzygroup/polly,13,Want to run an eventr,[],[],open,2025-04-26T16:45:59Z,https://github.com/fuzzygroup/polly/issues/13
43,fuzzygroup/polly,12,Actions,[],[],open,2025-04-26T13:18:20Z,https://github.com/fuzzygroup/polly/issues/12
44,fuzzygroup/polly,11,Need to easily track who is available for an event or a time span,[],[],open,2025-04-26T13:16:40Z,https://github.com/fuzzygroup/polly/issues/11
45,fuzzygroup/polly,10,Implement Graphics Review via a Flier Object,[],[],open,2025-04-26T13:13:38Z,https://github.com/fuzzygroup/polly/issues/10
46,fuzzygroup/polly,9,Figure out what has gone wrong with Vobject,[],[],open,2025-04-25T15:14:08Z,https://github.com/fuzzygroup/polly/issues/9
47,fuzzygroup/polly,8,Implement User Badging,[],[],open,2025-04-25T15:11:16Z,https://github.com/fuzzygroup/polly/issues/8
48,fuzzygroup/polly,7,Add in support for new Rails 8 Mail integration to allow capturing input from different emails sent to an org and clustering their results for analysis,[],[],open,2025-04-25T14:35:08Z,https://github.com/fuzzygroup/polly/issues/7
49,fuzzygroup/polly,6,Current dev environment is broken due to deploy changes faking the environment into thinking its actually wrong,[],[],open,2025-04-25T01:47:19Z,https://github.com/fuzzygroup/polly/issues/6

📌 Filtered Issues for: fuzzygroup/policounter

,repo,id,title,assignees,labels,state,created_at,url
0,fuzzygroup/policounter,35,change readme for project,[],[],open,2025-07-08T18:46:15Z,https://github.com/fuzzygroup/policounter/issues/35
1,fuzzygroup/policounter,34,switch to post from get,[],[],open,2025-07-08T18:14:13Z,https://github.com/fuzzygroup/policounter/issues/34
2,fuzzygroup/policounter,33,lock up communication to polly,[],[],open,2025-07-08T18:13:15Z,https://github.com/fuzzygroup/policounter/issues/33
3,fuzzygroup/policounter,32,expose event fields to the UI,[],[enhancement],open,2025-05-09T05:12:09Z,https://github.com/fuzzygroup/policounter/issues/32
4,fuzzygroup/policounter,31,count should be integer,[tetrismegistus],[bug],open,2025-05-09T04:02:32Z,https://github.com/fuzzygroup/policounter/issues/31
5,fuzzygroup/policounter,29,expose observation fields to UI,[tetrismegistus],[enhancement],open,2025-05-09T01:53:01Z,https://github.com/fuzzygroup/policounter/issues/29
6,fuzzygroup/policounter,26,Get Policounter UI cleaned up -- OVERALL TICKET,[tetrismegistus],[],open,2025-04-28T13:20:09Z,https://github.com/fuzzygroup/policounter/issues/26
7,fuzzygroup/policounter,24,Write an essay about HOW TO MEASURE CROWDS for grass roots political activity,[tetrismegistus],[documentation],open,2025-04-25T17:48:25Z,https://github.com/fuzzygroup/policounter/issues/24
8,fuzzygroup/policounter,23,DB backup,[tetrismegistus],[enhancement],open,2025-04-25T17:47:37Z,https://github.com/fuzzygroup/policounter/issues/23
9,fuzzygroup/policounter,21,rebuild the architecture around a sharing model (using a share of 1 of 3 types per whiteboard discussion),[tetrismegistus],[enhancement],open,2025-04-25T17:46:20Z,https://github.com/fuzzygroup/policounter/issues/21
10,fuzzygroup/policounter,20,Explain the Models,[tetrismegistus],[documentation],open,2025-04-25T17:39:58Z,https://github.com/fuzzygroup/policounter/issues/20
11,fuzzygroup/policounter,17,Understand the rails api for DEVISE gem,[tetrismegistus],[documentation],open,2025-04-25T17:33:13Z,https://github.com/fuzzygroup/policounter/issues/17
12,fuzzygroup/policounter,16,Generate a map view by day / over time or a density view or something that shows trending,[tetrismegistus],[enhancement],open,2025-04-25T17:22:53Z,https://github.com/fuzzygroup/policounter/issues/16
13,fuzzygroup/policounter,15,Improve the language around the estimates so it is human readable,[tetrismegistus],[enhancement],open,2025-04-25T17:21:51Z,https://github.com/fuzzygroup/policounter/issues/15
14,fuzzygroup/policounter,13,Need to be able to export a CSV,[tetrismegistus],[enhancement],open,2025-04-25T17:17:49Z,https://github.com/fuzzygroup/policounter/issues/13
15,fuzzygroup/policounter,10,Need to extract location metadata from images,[tetrismegistus],[enhancement],open,2025-04-25T17:16:01Z,https://github.com/fuzzygroup/policounter/issues/10
16,fuzzygroup/policounter,9,Need to support location based permalinks,[tetrismegistus],[enhancement],open,2025-04-25T17:15:37Z,https://github.com/fuzzygroup/policounter/issues/9
17,fuzzygroup/policounter,5,Make it so images can't be crawled so easily,[tetrismegistus],[enhancement],open,2025-04-25T11:26:01Z,https://github.com/fuzzygroup/policounter/issues/5

In [3]:
df.save("issues.csv")

NameError: name 'df' is not defined